### ISSUE TITLE
[Feature] Set default monitor converter

### ISSUE THREAD

**Issue by kvnkho** [fugue-project/tune#50]
**Is your feature request related to a problem? Please describe.**

When using a monitor, 
```python
result = suggest_keras_models_by_sha(
    space.sample(16,0),
    plan=[(warmup+1.0,8),(2.0,4),(4.0,2),(8.0,1)],
    execution_engine_conf={"callback":True},
    monitor="rungs",
    top_n=2,
)
```
raises
```
TuneCompileError: rungs can't be converted to Monitor
```
because there is not default set on [this line](https://github.com/fugue-project/tune/blob/eff7c7c02bd3cbffe64657f87cad0e4412f55862/tune/factory.py#L136). Ideally, this is something that can be handled by default by all of the `suggest_` functions.

**Describe the solution you'd like**

Right now, there is some manual code that needs to be added to get it working. This should just be the default behavior.

```python
from typing import Optional
from tune import Monitor
from tune_notebook import (
    NotebookSimpleHist,
    NotebookSimpleRungs,
    NotebookSimpleTimeSeries,
    PrintBest,
)

def to_monitor(obj) -> Optional[Monitor]:
    if obj is None:
        return None
    if isinstance(obj, Monitor):
        return obj
    if isinstance(obj, str):
        if obj == "hist":
            return NotebookSimpleHist()
        if obj == "rungs":
            return NotebookSimpleRungs()
        if obj == "ts":
            return NotebookSimpleTimeSeries()
        if obj == "text":
            return PrintBest()
    raise NotImplementedError(obj)

TUNE_OBJECT_FACTORY.set_monitor_converter(to_monitor)
```

**Comment by goodwanghan** [comment]
We are switching to plugin design pattern. These will become automatic.

https://github.com/fugue-project/tune/blob/04509adf8dfe0c6c7bb5e5801d574b7e227920f5/tune_notebook/monitors.py#L10-L33
